language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: PHPCS=1 DEFAULT=0

    - php: 7.0
      env: CODECOVERAGE=1 DEFAULT=0 DB=mysql db_dsn='mysql://travis@0.0.0.0/cakephp_test'

    - php: 7.1
      env: DB=pgsql db_dsn='postgres://postgres@127.0.0.1/cakephp_test'

    - php: 7.1
      env: DB=sqlite db_dsn='sqlite:///:memory:'

  allow_failures:
    - php: 7.1
      env: DB=pgsql db_dsn='postgres://postgres@127.0.0.1/cakephp_test'

before_script:
  - phpenv config-rm xdebug.ini

  - composer install --prefer-dist --no-interaction

  - if [[ $DB == 'mysql' ]]; then mysql -e 'CREATE DATABASE cakephp_test;' ; fi
  - if [[ $DB == 'pgsql' ]]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres ; fi

  - if [[ $PHPCS != 1 ]]; then composer require --dev phpunit/phpunit:"*" ; fi

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit; fi

  - if [[ $PHPCS == 1 ]]; then composer cs-check ; fi

  - if [[ $CODECOVERAGE == 1 ]]; then vendor/bin/phpunit --coverage-clover=clover.xml || true ; fi
  - if [[ $CODECOVERAGE == 1 ]]; then wget -O codecov.sh https://codecov.io/bash ; fi
  - if [[ $CODECOVERAGE == 1 ]]; then bash codecov.sh ; fi

notifications:
  email: false
